### ISSUE TITLE
How remove followers sales ... form navbar user

### ISSUE THREAD

**Issue by Malstrom** [avanzu/AdminThemeBundle#110]
<img width="322" alt="schermata 2016-06-12 alle 13 47 48" src="https://cloud.githubusercontent.com/assets/1248044/15990974/57ae0844-30a4-11e6-9e86-48f723f92e1b.png">

**Comment by avanzu** [comment]
Following the guide on how to [override](http://symfony.com/doc/current/book/templating.html#overriding-bundle-templates) bundle templates, you copy the template file (Resources/views/Navbar/user.html.twig) to the appropriate folder in your application and customize this file to your needs.

**Comment by Malstrom** [comment]
Thanks a lot!
