### ISSUE TITLE
starter.html

### ISSUE THREAD

**Issue by hounded** [avanzu/AdminThemeBundle#113]
The "vendor/almasaeed2010/adminlte/starter.html" directory does not exist.

when running avanzu:admin:initialize on windows

**Comment by avanzu** [comment]
This should be fixed with the latest [pre-release](https://github.com/avanzu/AdminThemeBundle/releases/tag/2.0.0-beta.4). 

Rather than excluding `starter.html`, the command will now support specific file copies and not just directories. I guess, this makes #131 obsolete?

**Comment by hounded** [comment]
yup, PR closed
