### ISSUE TITLE
Breaks after new AdminLTE release (2.3.4/2.3.5)

### ISSUE THREAD

**Issue by elmariachi111** [avanzu/AdminThemeBundle#115]
The new template release 2.3.5. breaks this package. I'm currently falling back on a dirty quick fix, using my own fork. If it's not working for you, try to use version 2.3.3: 
- Fork this repo.
- Edit vendor/admin-theme-bundle/Resources/bower/bower.json:
  
  ```
  dependencies: {
     ...
      adminlte: "2.3.3"
  }
  ```
- Update your composer.json

```
require: {
    ...
    "avanzu/admin-theme-bundle": "dev-master",
    ...
},
repositories: [
       ...
       {
      "type": "vcs",
      "url": "https://github.com/<your-fork-basename>/AdminThemeBundle"
    }
    ]
```
- composer update (pkg)

fetch and build commands should run now.

**Comment by hjanuschka** [comment]
you mean the break because of #117 ?
with #117  applied it builds fine.

**Comment by elmariachi111** [comment]
jep ;) Works well with my own fallback, so I'm going with that one for now. Hope that #117 is merged soon...

**Comment by avanzu** [comment]
Merged #117 - please take into account that the 2.0 release will soon be merged back into the master branch.

**Comment by shakaran** [comment]
@elmariachi111 do you still have problems with this issue or has been resolved?

**Comment by shakaran** [comment]
@elmariachi111 I gonna close this issue since other users are using 2.3.X upper versions and it seems all resolved. Please reopen if you still found problems in future related to this. Thanks!
