### ISSUE TITLE
bower error

### ISSUE THREAD

**Issue by hjanuschka** [avanzu/AdminThemeBundle#116]
unable to process "/Users/hjanuschka/backend/FXF/web/bundles/avanzuadmintheme/vendor/adminlte/plugins/daterangepicker/daterangepicker-bs3.css" with Error: ENOENT: no such file or directory, open '/Users/hjanuschka/backend/FXF/web/bundles/avanzuadmintheme/vendor/adminlte/plugins/daterangepicker/daterangepicker-bs3.css'

**Comment by OskarStark** [comment]
Does #117 fix your problem?

**Comment by hjanuschka** [comment]
yeah i think this should fix it can you merge it

**Comment by avanzu** [comment]
see #115
