### ISSUE TITLE
Missing styles "_all.css"

### ISSUE THREAD

**Issue by OndrejPiza** [avanzu/AdminThemeBundle#120]
Hi,

I'm trying to use gulp with concatCSS to concat and later minimize my css files. The problem I ran into is that there are some missing css files, namely 

```
@import url("minimal/_all.css");
@import url("square/_all.css");
@import url("flat/_all.css");
@import url("line/_all.css");
@import url("polaris/polaris.css");
@import url("futurico/futurico.css");
```

So gulp  will cause and exception. I'm using admin-lte-all.css ... should I use different one or is there something I'm missing. It in the "Timepicker Component for Twitter Bootstrap" section.

Thank you

**Comment by avanzu** [comment]
If you're about to concat and minify the assets by yourself, you might end up with a smaller footprint by avoiding the pre-packaged files all together and rather use the theme assets as they are provided. 

For reference, please have a look at the [asset group listings](https://github.com/avanzu/AdminThemeBundle/blob/master/Resources/docs/layout.md) and into the [assets.php](https://github.com/avanzu/AdminThemeBundle/blob/master/Resources/config/assets.php) to look up the correct directories and filenames.
