### ISSUE TITLE
daterangepicker-bs3.css" does not exist

### ISSUE THREAD

**Issue by bilougit** [avanzu/AdminThemeBundle#125]
``` json
"version": "1.3.4",
```
#117 when is this going to be released on 1.3? What can I do meanwhile?

Thx,

**Comment by JoeRobles** [comment]
Hey guys, it's been 3 months from last comment, could you please accept this pull request? Thank you.

**Comment by maxvanceffer** [comment]
Yeap pleeeeese !!!

**Comment by chteuchteu** [comment]
Ping @avanzu

**Comment by darthf1** [comment]
Would be great to see this releases soon.

**Comment by shakaran** [comment]
@bilougit since #117 has been merged, your issue should be resolved. Please confirm if you can

@chteuchteu This issue probably could be closed

**Comment by shakaran** [comment]
Closing since it seems all fixed. Please reopen if you still have problems

**Comment by plozmun** [comment]
This bug exists on stable 1.3.5 version

**Comment by shakaran** [comment]
Fixed by your https://github.com/avanzu/AdminThemeBundle/pull/186 Closing again
