### ISSUE TITLE
Command error

### ISSUE THREAD

**Issue by fcpauldiaz** [avanzu/AdminThemeBundle#126]
The command avanzu:admin:fetch-vendor gives There are no commands defined in the "avanzu:admin" namespace. 

Using 2.3.5

**Comment by avanzu** [comment]
Did you enable the bundle in `AppKernel`?  I assume "Using 2.3.5" means Symfony 2.3.5?

**Comment by shakaran** [comment]
@fcpauldiaz do you have still this problem? Probably you need enable the bundle in AppKernel if not the avanzu commands will not be present. Please let me know the status about this, so we can close the issue if resolved

**Comment by fcpauldiaz** [comment]
I'm closing this, I'm not using this bundle currently

**Comment by dan-coman** [comment]
I have the same error when trying to run `avanzu:admin` on symfony 4 with the dev-master version. Any news about this?
