### ISSUE TITLE
bootflat package no longer exists

### ISSUE THREAD

**Issue by bobvandevijver** [avanzu/AdminThemeBundle#129]
The bootflat package in the bower.json file no longer exists. I've created a workaround by changing it to bootflatv2, but I'm not sure if that's correct.

**Comment by shakaran** [comment]
@bobvandevijver would you mind make a Pull Request for the change? Thanks

**Comment by bobvandevijver** [comment]
Not at this moment, no. First I will have to check what the current state is, I no longer have the exact change available.

**Comment by shakaran** [comment]
@bobvandevijver ok, take your time needed, thanks

**Comment by shakaran** [comment]
@bobvandevijver I just update the depency. So I gonna close this issue, if you found problems in future with the use of new dependency. Just le me know or reopen this issue. Thanks for your reporting!
