### ISSUE TITLE
Bower not found

### ISSUE THREAD

**Issue by andho** [avanzu/AdminThemeBundle#130]
Bower is in my user path: /home/{user}/.local/bin/bower.

```
php bin/console avanzu:admin:fetch-vendor
[Executing] /usr/local/bin/bower install 
[Error] sh: 1: /usr/local/bin/bower: not found
```

Why does it use an absolute path to bower instead of depending on the PATH?

**Comment by avanzu** [comment]
Configure your path as [described here](https://github.com/avanzu/AdminThemeBundle/blob/master/Resources/docs/rebuild.md#install-vendor-scripts) and you should be good to go.
