### ISSUE TITLE
Layout Error with version 2.0

### ISSUE THREAD

**Issue by graille** [avanzu/AdminThemeBundle#133]
Hi !

I have an error with the new release of the 2.0 version of the Theme :

> Unknown "admin_style_path" function in AvanzuAdminThemeBundle:layout:base-layout.html.twig at line 17.

The code :

`{% block stylesheets %}
        <link rel="stylesheet" href="{{ asset(admin_style_path()) }}" />
    {% endblock %}
`

Any idea ? :)

**Comment by fr05t1k** [comment]
https://github.com/avanzu/AdminThemeBundle/issues/121 maby you can answer here

**Comment by shakaran** [comment]
This issue could be help on issue recopilatory #165

**Comment by shakaran** [comment]
Closing this issue since #168 has been merged. Thanks!
