### ISSUE TITLE
KnpMenu 2nd level iOS touch

### ISSUE THREAD

**Issue by hounded** [avanzu/AdminThemeBundle#134]
dev/2.0 
using the KNP menu with two levels, the menu does not expand on touch on safari
works on click 

Any help much appreciated,

cheers

**Comment by hounded** [comment]
http://stackoverflow.com/questions/14795944/jquery-click-events-not-working-in-ios

adding to theme/dist/css/AdminLTE.min.css
.sidebar-menu
{
list-style:none;
margin:0;
padding:0;
cursor:pointer;
}
fixes it

**Comment by shakaran** [comment]
@hounded would you mind make a PR with the changes that you highlight? Thanks

**Comment by shakaran** [comment]
@hounded the admilte version was upgraded with some minor changes in master. I am not sure if this is affecting anymore to the sidebar-menu. Probably it is a better option modify in 

`./vendor/almasaeed2010/adminlte/dist/css/skins/_all-skins.css`

In any case, probably is it an issue to report at [almasaeed2010/adminlte](https://github.com/almasaeed2010/AdminLTE) which is the upstream for that part. So I gonna close this issue for that, but you can reopen again if you consider needed.
