### ISSUE TITLE
Styling not showing

### ISSUE THREAD

**Issue by ghost** [avanzu/AdminThemeBundle#142]
I have followed the readme file exactly. It seems to work, but I don't get the necessary styles applied.

This is what I have after following the readme;

![screenshot from 2016-10-13 14-00-12](https://cloud.githubusercontent.com/assets/16900286/19348262/71b8d0fc-914d-11e6-9500-1bc8fa3350f3.png)

Can anybody please tell me what I'm doing wrong? Or did I forgot something, because I'm already through the installation guide (readme) like 4 times.

I have installed the assets, and I have fetched the vendors, but by doing that I did get some bower messages like this;

> [Error] bower invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes
> [Error] bower ionicons#\* invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes
> [Error] bower ionicons#\* invalid-meta The "main" field cannot contain globs (example: "_.js")
> [Error] bower ionicons#_ mismatch Version declared in the json (2.0.0) is different than the resolved one (2.0.1)
> [Error] bower pickadate#\* invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .js files: ["lib/picker.js","lib/picker.date.js
> [Error] bower pickadate#\* invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .css files: ["lib/themes/default.css","lib/themes/default.date.css","lib/themes/default.time.css"]
> [Error] bower adminlte#>=2.0.0 <3.0 invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes
> [Error] bower backbone.radio#2.0.0-pre.1 mismatch Version declared in the json (1.0.4) is different than the resolved one (2.0.0-pre.1)

I don't know if this has to do with it. But please help me!

**Comment by tofra** [comment]
Have you run the commands below?

```
php bin/console assets:install --symlink
php bin/console avanzu:admin:initialize [--symlink|--relative]
```

**Comment by Mentos93** [comment]
I have done the first command yes, and the second one is not defined!

**Comment by tofra** [comment]
What is the exact command you used?

**Comment by rawburner** [comment]
Same issue for me, but only in dev env. All bower commands worked without errors, but the file web/bundles/avanzuadmintheme/static/dev/styles/admin-lte-all.css stay empty.
First I had the error that web/bundles/avanzuadmintheme/vendor/adminlte/plugins/daterangepicker/daterangepicker-bs3.css could not be found, I needed to change it to 
web/bundles/avanzuadmintheme/vendor/adminlte/plugins/daterangepicker/daterangepicker.css then assets has been build.
I can see all styles on prod env but not on dev. Please help.

**Comment by shakaran** [comment]
For some reason the command:

php bin/console avanzu:admin:initialize [--symlink|--relative]

Has been removed, and fetch vendor and build-assets command should be used, but if you get errors, it will show you blank page, so this must be fixed

**Comment by shakaran** [comment]
@rawburner and others. This issue has been fixed in master branch. Please test and reopen if you have issues. Closing as fixed
