### ISSUE TITLE
Sidebar menu displaying only the last item.

### ISSUE THREAD

**Issue by caio-baracat** [avanzu/AdminThemeBundle#149]
Sidebar is displaying only the last menu item.
I created my own event and even copied the given example but nothing.
So i looked into `SidebarMenuEvent.php` and changed this on line 59 `$this->menuRootItems[] = $item;` and worked. But i know that there is something wrong. Here is my code:

[http://pastebin.com/WS8YxBza](http://pastebin.com/WS8YxBza)

What am i doing wrong?

**Comment by caio-baracat** [comment]
Nevermind.
I realize that the ItemId are all the same.

What a shame. Sorry

**Comment by chteuchteu** [comment]
Alright, this issue can be closed then!
