### ISSUE TITLE
FosUserBundle problem

### ISSUE THREAD

**Issue by maxvanceffer** [avanzu/AdminThemeBundle#154]
Using this bundle and FosUserBundel together my user class looks like this:

class User extends BaseUser implements ThemeUser {}

But when i try to generate new user from console, generated sql is missing salt !! So user can not be created.

**Comment by chteuchteu** [comment]
I'm using the same class signature in one of my projects, and everything works fine. Are you sure that AdminThemeBundle is the conflicting project here?
If you browse `ThemeUser` code, you'll see that it only provides an interface for some template methods (such as `getAvatar`, `isOnline`, ...)

**Comment by tofra** [comment]
Do you use encoder BCrypt? If yes, then it's pretty normal that salt is empty as it doesn't use salt..
```
security.yml
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
```

**Comment by shakaran** [comment]
@maxvanceffer after read the comments, this was an issue from FoSUserBundle or AdminThemeBundle? So we can clean the issue or retake if affects you

**Comment by shakaran** [comment]
@maxvanceffer I would thank you if you can give me some feedback about this. If I don't have any clue or news, probably I will close this issue next week, but you can reopen in any moment if you found the issue again in a future

**Comment by shakaran** [comment]
Closing as won'tfix since no feedback received. Please reopen if you still have the issue in future
