### ISSUE TITLE
How To Implement Navbar User Component

### ISSUE THREAD

**Issue by torkium** [avanzu/AdminThemeBundle#155]
Hello,
I am trying to implement Navbar User Component and I can not get it...

In MyAdminBundle\Model\UserModel , we must implement interface methods, but i do not find anywhere how to implement there, what value must return, etc etc...

for example, whate getAvatar must return?

Can someone help me?

Did you have any example?

Thank you

**Comment by lucasaba** [comment]
Hi torkium,
could you be more specific. I think the documentation is clear enough (https://github.com/avanzu/AdminThemeBundle/blob/1.3.4/Resources/docs/navbar_user.md).

And so is the interface. If you implement it (Avanzu\AdminThemeBundle\Model\UserInterface) you can return bogus values and see wath goes wrong.

By the way, getUser must return a path to the user image. E.g:

```
public function getAvatar()
{
    return 'images/avatar.png';
}
```

Would result in the following html

```
<img src="/images/avatar.png" class="user-image" alt="username">
```

**Comment by torkium** [comment]
Thanks;),

I managed to implement the components yesterday after asking these questions


Interface methods should be documented :p

I close the issue, thanks again !

**Comment by lucasaba** [comment]
:+1: 

> Interface methods should be documented
