### ISSUE TITLE
Datatable rowreorder plugin

### ISSUE THREAD

**Issue by hvalcourtSerdy** [avanzu/AdminThemeBundle#157]
Hi,

just for let you know,

 the last version of rowreorder plugin of datatable ( https://datatables.net/extensions/rowreorder/ ) is not compatable with the js included in admin_lte_js (scripts/admin-lte.js).

Error in the js console : 'DataTables RowReorder requires DataTables 1.10.8 or newer';

Is it possible to update the bundle eventually ?

Thanks,

Hugo

**Comment by shakaran** [comment]
@hvalcourtSerdy if you have knowledge to make a PR, I recommend you prepare one to speed up the change! Thanks

**Comment by shakaran** [comment]
@hvalcourtSerdy I update master with some changes and update admin-lte.js (now called app.js). Please test again and let me know if the issue still persist, thanks!

**Comment by shakaran** [comment]
@hvalcourtSerdy I see that adminlte is using DataTables 1.10.15 in his bower.json. So I think that this issue should be fixed. I gonna close it, but reopen if you still found the issue present in master. Thanks!
