### ISSUE TITLE
How to customize colors?

### ISSUE THREAD

**Issue by Filoz** [avanzu/AdminThemeBundle#161]
Hi, 
I know that is possible to set the colors for every components using css...

But if how can be done customizing the variable.less file of AdminLTE?

**Comment by chteuchteu** [comment]
You cannot reliably edit AdminThemeBundle internal files (when using ATB as a direct composer dependency).
You could 
- fork the project, edit it, and publish it as a composer dependency for your own usage
- add a CSS file in your own project, overriding AdminLTE's components

**Comment by Filoz** [comment]
thankyou!
I override AdminLte skin :)
