### ISSUE TITLE
Menu infinite child

### ISSUE THREAD

**Issue by Filoz** [avanzu/AdminThemeBundle#163]
Hi, there are two different pull request that  add a new feature to navigation menu, 
can one of them be merged?

https://github.com/avanzu/AdminThemeBundle/pull/162

https://github.com/avanzu/AdminThemeBundle/pull/97

**Comment by shakaran** [comment]
@Filoz Both have different changes, it will need to be reviewed to take one or other or update bettwen the both the better changes

**Comment by shakaran** [comment]
@Filoz changes merged in master. Thanks for your issue reported! Closing
