### ISSUE TITLE
Widget blocks do not exist

### ISSUE THREAD

**Issue by benr77** [avanzu/AdminThemeBundle#164]
I've just upgraded my project from Twig 1.x to Twig 2.x and I'm getting the following errors about missing blocks:

`Block "box_before" on template "AvanzuAdminThemeBundle:Widgets:box-widget.html.twig" does not exist.`

This is in file

`vendor/avanzu/admin-theme-bundle/Resources/views/Widgets/box-widget.html.twig at line 2 `

I'm using the latest Beta 5 release. 

I think this is because Twig 1.x silently ignores undefined blocks, whereas Twig 2.x throws an exception.

The issue crops up for all the blocks defined for the widget - e.g. box_tools, box_after etc etc

**Comment by hounded** [comment]
submit a pull request?

**Comment by shakaran** [comment]
@benr77 the PR #169 has been merged, this resolve all your issue or still present? Thanks

**Comment by benr77** [comment]
Yes this was all that was needed.
