### ISSUE TITLE
ECONFLICT Unable to find suitable version for jquery

### ISSUE THREAD

**Issue by infinitely-young** [avanzu/AdminThemeBundle#174]
Could not find jquery while building assets. Solution could be to add resolutions to bower.json
{
  "dependencies": {
    "jquery": "~1.11.1",
  },
 ...
  "resolutions": {
    "jquery": "~1.11.1"
  }
}

**Comment by albertsola** [comment]
After setting jquery to 1.11.1 as you mentioned datatables plugin gone missing.

@AvanzuAdminThemeBundle/Resources/public/vendor/adminlte/plugins/datatables/

**Comment by MehGokalp** [comment]
@albertsola Your solution here: https://github.com/avanzu/AdminThemeBundle/issues/175

**Comment by shakaran** [comment]
@albertsola I update master branch with the change, please let me know if it resolves the issue for you, so I can close the issue. Thanks!

**Comment by infinitely-young** [comment]
@shakaran We also found that bug was with adminlte version. This is it! I think that we can close this issue due to your update in master branch. Thx a lot!
