### ISSUE TITLE
Adminlte version 2.4 crashes adminthemebundle

### ISSUE THREAD

**Issue by MehGokalp** [avanzu/AdminThemeBundle#175]
[Adminlte](https://github.com/almasaeed2010/AdminLTE/releases) version 2.4 released 3 days ago, in Resources/Bower/Bower.json, adminlte version range is [">=2.0.0 <3.0"](https://github.com/avanzu/AdminThemeBundle/blob/master/Resources/bower/bower.json#L34) so it fetch 2.4 and assset:install script crashes.

**Solution**: change [line 34 in bower.json](https://github.com/avanzu/AdminThemeBundle/blob/master/Resources/bower/bower.json#L34) ">=2.0.0 <3.0" to "~2.3" and it'll work

**Comment by shakaran** [comment]
@MehGokalp could you make an pull request for this? I don't have this issue fetching with latest master, so I am not sure if you are testing the same version

**Comment by nehalist** [comment]
+1

**Comment by shakaran** [comment]
@MehGokalp @nehalist I update master branch with the change, please let me know if it resolves the issue for you, so I can close the issue. Thanks!

**Comment by MehGokalp** [comment]
Now, composer throws exception in `composer update`

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for avanzu/admin-theme-bundle dev-master -> satisfiable by avanzu/admin-theme-bundle[dev-master].
    - Conclusion: don't install almasaeed2010/adminlte v2.4.0
    - avanzu/admin-theme-bundle dev-master requires almasaeed2010/adminlte ~2.3.0 -> satisfiable by almasaeed2010/adminlte[v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.2, v2.3.3, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9].
    - Can only install one of: almasaeed2010/adminlte[v2.3.0, v2.4.0].
    - Can only install one of: almasaeed2010/adminlte[v2.3.1, v2.4.0].
    - Can only install one of: almasaeed2010/adminlte[v2.3.10, v2.4.0].
    - Can only install one of: almasaeed2010/adminlte[v2.3.11, v2.4.0].
    - Can only install one of: almasaeed2010/adminlte[v2.3.2, v2.4.0].
    - Can only install one of: almasaeed2010/adminlte[v2.3.3, v2.4.0].
    - Can only install one of: almasaeed2010/adminlte[v2.3.4, v2.4.0].
    - Can only install one of: almasaeed2010/adminlte[v2.3.5, v2.4.0].
    - Can only install one of: almasaeed2010/adminlte[v2.3.6, v2.4.0].
    - Can only install one of: almasaeed2010/adminlte[v2.3.7, v2.4.0].
    - Can only install one of: almasaeed2010/adminlte[v2.3.8, v2.4.0].
    - Can only install one of: almasaeed2010/adminlte[v2.3.9, v2.4.0].
    - Installation request for almasaeed2010/adminlte (locked at v2.4.0) -> satisfiable by almasaeed2010/adminlte[v2.4.0].

**Comment by shakaran** [comment]
@MehGokalp that's is because you have locked in composer.lock the version 2.4.0. Actually the composer version is indicating you that you can install up to 2.3.9. The change for the PR #177 should work fine if you remove your previous 2.4.0

**Comment by MehGokalp** [comment]
I'm not sure why it's forced to fetch v2.4. I'll take care of it later, but you must append fixes to 1.3.4 version that you resolve them in this week (https://github.com/avanzu/AdminThemeBundle/issues/174, also this issue and others)

**Comment by shakaran** [comment]
@MehGokalp for 1.3 branch I just release 1.3.5 as hotfix that should restrict to use adminlte 2.3.x version and don't use admin-lte 2.4.0 just released

**Comment by shakaran** [comment]
I gonna temptative close this issue since other users are reported that it is fixed. Please reopen if you still have issues with this. Thanks!
