### ISSUE TITLE
Neither the property "control_sidebar" nor one of the methods... from scratch

### ISSUE THREAD

**Issue by glerendegui** [avanzu/AdminThemeBundle#182]
I cant make this bundle work. 

- I have created a new project, I've installed the bundle with:
 _php composer.phar require avanzu/admin-theme-bundle dev-master_
- Added the bundle to the AppKernel
- Installed assets
- Created a new empty template as:
```
{% extends 'AvanzuAdminThemeBundle:layout:default-layout.html.twig' %}


{% block avanzu_page_content  %}
{{parent()}}
Hello World
{% endblock %}
```

- No config at all
But when I load this template I get:

```
_Neither the property "control_sidebar" nor one of the methods "control_sidebar()", "getcontrol_sidebar()"/"iscontrol_sidebar()" or "__call()" exist and have public access in class "Avanzu\AdminThemeBundle\Helper\ContextHelper"._
in vendor/avanzu/admin-theme-bundle/Resources/views/layout/default-layout.html.twig at line 225 
```

**Comment by glerendegui** [comment]
The problem still remains after update. 
More info.
The problem is around vendor/avanzu/admin-theme-bundle/Resources/views/layout/default-layout.html.twig at line 225 and 342
`{% if avanzu_admin_context.control_sidebar %}`

If I jump this condition with "false and", the problem changes to "Neither the property knp_menu... " at line 253 and 314:
`{% if avanzu_admin_context.knp_menu.enable %}`

Clearly it's a problem with avanzu_admin_context properties. If I dump that I get
```
ContextHelper {#564 ▼
  -router: RouteAliasCollection {#556 ▼
    #cacheDir: "/path-to-my-project/code/var/cache/dev"
    #router: Router {#342 ▶}
    #routeAliases: array:1 [▶]
    #optionName: "avanzu_admin_route"
    #env: "dev"
    -debug: true
  }
  flag::STD_PROP_LIST: false
  flag::ARRAY_AS_PROPS: false
  iteratorClass: "ArrayIterator"
  storage: []
}
```

I haven't changed nothing at all in config files. Just composed bundle and tested template.

**Comment by shakaran** [comment]
@glerendegui test again with master when you can, thanks!

**Comment by glerendegui** [comment]
Perfect! Very thanks!

**Comment by shakaran** [comment]
@glerendegui glad that it was perfectly fixed ;) I would need a lot testing from old users and  power users before to release master as stable, but your comments and issues are always welcome.

In other hand, I am not very sure if the MenuBuilder and KpnMenuBuilder is working like 1.3 releases, so any full testing and complex config or heavy uses are always welcome!
