### ISSUE TITLE
datepicker not working

### ISSUE THREAD

**Issue by glerendegui** [avanzu/AdminThemeBundle#188]
Date form fields are not working. The datepicker are not showed.
I have a template like Default/form.html.twig with
```
            $('input').iCheck({
                checkboxClass: 'icheckbox_square-blue',
                radioClass: 'iradio_square-blue',
                increaseArea: '20%' // optional
            });
            $('select').select2();
            $('[data-datepicker="on"]').datepicker({autoclose: true});
            $('[data-timepicker="on"]').timepicker();
```

but nothing happens. When I have looked inside bootstrap-datepicker.js I have found that data-dapicker is something used inside the library, so, after change my code to:
`$('[data-datepickerenable="on"]').datepicker({autoclose: true});`

and after change form-theme.html.twig, block date_widget for
`{% set attr = attr|merge({'class' : class, 'data-datepicker enable':'on'}) %}`

it started working.

### Debug info

| Component  | Version |
| ------------- | ------------- |
| Symfony version  | 3.2  |
| AdminThemeBundle  | dev-master  |

**Comment by shakaran** [comment]
@glerendegui I push a fix now following your comment, please test latest master and let me know if work fine for you, thanks!

**Comment by glerendegui** [comment]
@shakaran The fix it's not working because my original copy has an error. 
data-datepicker cant be used.
The fix its to use:
{% set attr = attr|merge({'class' : class, 'data-datepickerenable':'on'}) %}

data-datepickerenable without spaces. It can be "data-datepicker_enable" or anything but "data-datepicker" because that's used by the javascript plugin.

**Comment by shakaran** [comment]
@glerendegui pushed the change, let me know if the fix works for you

**Comment by shakaran** [comment]
@glerendegui ping again, please let me know the status so I can close this issue, thanks!

**Comment by glerendegui** [comment]
I can confirm that it's fixed. I'm sorry for the delay.

**Comment by shakaran** [comment]
@glerendegui Thanks a lot ;) Closing the issue
