### ISSUE TITLE
Unable to use the control sidebar

### ISSUE THREAD

**Issue by romainlaisne** [avanzu/AdminThemeBundle#193]
Hi,

I am using your bundle and it works pretty good.
However, I am unable to have the control sidebar (right side) working= folding/unfolding.

In Avanzu base layout, I am loading all css like this

`{% block stylesheets %}
        <link rel="stylesheet" href="{{ asset('bundles/avanzuadmintheme/static/'~ app.environment ~'/styles/admin-lte-all.css') }}" />
    {% endblock %}`

JS are loaded like that:
`<script type='text/javascript' src="{{ asset('bundles/avanzuadmintheme/static/'~app.environment~'/scripts/admin-lte-all.js') }}"></script>`

**Note : The sidebar on the left works properly.**

I have a cog icon to trigger the control sidebar
`<a href="javascript: void(0);" data-toggle="control-sidebar" data-direction="rtl" role="button">
                <i class="fa fa-cog fs-16"></i>`

And the sidebar itself
`<aside class="control-sidebar control-sidebar-dark">TEST SIDEBAR </aside>`

Any idea what's wrong here?
Do I miss any plugin or js to make that work?
It seems that the left navigation works the same way, isn't it?

**Comment by shakaran** [comment]
@romainlaisne are you using 1.3.x version or master or some 2.x beta?

Could you push your code or demo in some repo, so I could clone and debug which is happening in your fold/unfold?

**Comment by romainlaisne** [comment]
I took a radical approach and rebuild my template from scratch from adminlte demo. Now it works. I could see some tags where not ok in my earlier setup...perhaps a little more doc or a example on this bundle doc would be nice.
