### ISSUE TITLE
Badges are not aligned in menu

### ISSUE THREAD

**Issue by pabloveintimilla** [avanzu/AdminThemeBundle#195]
When you set a badge to a menu, this appear not aligned.

![captura de pantalla de 2017-11-07 19-41-56](https://user-images.githubusercontent.com/31135/32525827-4990d31a-c3f4-11e7-92e8-7d7fe5681d92.png)

### Debug info

| Component  | Version |
| ------------- | ------------- |
| Symfony version  | 3.3  |
| AdminThemeBundle  | 1.3.5/dev-master/  |

**Comment by shakaran** [comment]
I resolve the conflicts in your PR. Thanks for you contribution!
