### ISSUE TITLE
Unable to find file "@AvanzuAdminThemeBundle/Resources/public/vendor/spinjs/spin.js"

### ISSUE THREAD

**Issue by bpolaszek** [avanzu/AdminThemeBundle#203]
Hello there,

I'm using AdminThemeBundle 1.3.7 for several weeks and I needed to switch to an old branch of my project.

Now when I switch back to my project `master` branch and run `symfony avanzu:admin:fetch-vendor`, then go to any admin page, I've got this error.

### Debug info

| Component  | Version |
| ------------- | ------------- |
| Symfony version  | 3.3  |
| AdminThemeBundle  | 1.3.7  |

**Comment by shakaran** [comment]
Closing as fixed here and 1.3.8 released https://github.com/avanzu/AdminThemeBundle/commit/ed9a11f4c002bbc542adb680bddc5222e11e85a6
