### ISSUE TITLE
Error Awesome path

### ISSUE THREAD

**Issue by jlpilo** [avanzu/AdminThemeBundle#224]
Hi:

I deploy my proyect simfomy 3.4 with capistrano. All was ok but this week when I try to deploy it I get this error after execute "php bin/console assetic:dump  --no-debug";
"/var/www/web/releases/20180215071214/app/../web/bundles/avanzuadmintheme/vendor/fontawesome/css/font-awesome.min.css" does not exist"

If execute "php bin/console assetic:dump  --no-debug" from consele I get the same error too

It seems the awasome path had changed to: /web/bundles/avanzuadmintheme/vendor/fontawesome/web-fonts-with-css/css/font-awesome.min.css

I think is necesary to update avanzu, isnt??

Thanks

**Comment by xmontero** [comment]
In fact, this is a concrete instance of a recurrent generic problem with this bundle.

I think it tries to get always the "latest" versions of everything, whilst the dependencies via "composer" are thought to be "locked" so it does never break.

As avanzu's scripts run bower (like for example this line `/usr/local/bin/bower install --allow-root`) it is like "mixing" the composer ideas with the bower ideas. I'm very used to composer but no idea about bower.

Questions:
- Can bower "lock" the versions that it downloads?
- If yes, can avanzu/AdminThemeBundle commit some kind of "lock" to the tested versions so this will never break again?
- If not, can avanzu/AdminThemeBundle change the download mechanism to some other system that locks it?
- If not, could we switch to have avanzu/AdminThemeBundle to require some packages via composer itself? For example in this specific case, FontAwesome is available via https://packagist.org/packages/fortawesome/font-awesome and the versions could be much better controlled.

IDK if there's a forum or discussion place better than github to talk about this.

**Comment by shakaran** [comment]
Released 1.3.9 and master updated

https://github.com/avanzu/AdminThemeBundle/commit/3c9dbc92fc1e319095753c518ac10daf531b41e1

Closing as fixed

**Comment by jlpilo** [comment]
Perfect, very thanks
