### ISSUE TITLE
No assets were provided by any bundle

### ISSUE THREAD

**Issue by Manalro** [avanzu/AdminThemeBundle#228]
I have encountred an issue while trying to add the AdminLTE bundle to symfony. I am using the third version of symfony. I don't understand why it says that the assetswern't provided. Is it normal ? 

Here's the error :

 PS C:\wamp64\www\webis> php bin/console assets:install --symlink

 Trying to install assets as absolute symbolic links.

 [OK] No assets were provided by any bundle.

PS C:\wamp64\www\webis> php bin/console avanzu:admin:fetch-vendor

  There are no commands defined in the "avanzu:admin" namespace.

**Comment by shakaran** [comment]
@Manalro if you are using master (aka future 2.x version instead 1.3.x version) you need:

`php bin/console avanzu:admin:initialize`

Did you load the AppKernel too? with:

Enable the bundle in your kernel:

```php
<?php
// app/AppKernel.php

public function registerBundles()
{
	$bundles = array(
		// ...
		new Avanzu\AdminThemeBundle\AvanzuAdminThemeBundle(),
	);
}
```

**Comment by Manalro** [comment]
This was a mistake in my code.
This command works now
