### ISSUE TITLE
composer.json integration for fetch-vendors

### ISSUE THREAD

**Issue by glensc** [avanzu/AdminThemeBundle#23]
could you create scripts that could be put to projects composer.json to fetch vendor scripts:

```
app/console avanzu:admin:fetch-vendor
```

for example typical symfony application has:

```
    "scripts": {
        "post-install-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters", "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap", "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache", "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets", "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
        ],
        "post-update-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters", "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap", "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache", "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets", "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
        ]
    },
```

so, i think you need to create similar php code that could be appended to `post-update-cmd` and `post-install-cmd` sections!

**Comment by numerogeek** [comment]
@glensc Just add the following in composer.json : 
```javascript
        "post-install-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Avanzu\\AdminThemeBundle\\Composer\\ScriptHandler::fetchThemeVendors",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
        ],
```

**Comment by glensc** [comment]
@numerogeek when i created this ticket there was no ScriptHandler class in AdminThemeBundle

script handler was added in 8d7e7e3356dcd6ee9aadf204592e991af1f36d21 via #31 on Feb 25, 2015
while this ticket was created on Aug 11, 2014

@avanzu should review tickets more often, for example #25 is still not solved, nor #27

**Comment by shakaran** [comment]
@glensc @numerogeek as far the issue #29 could be rebased and update, probably it could be merged

**Comment by shakaran** [comment]
I add in the readme a comment about add autofetching after install/update in a composer symfony project. This the code for ScriptHandler is updated and the PR is outdated and after review the code is not needed anymore. I gonna close it. But reopen if you consider needed. Thanks for your contribution!
