### ISSUE TITLE
fetch-vendor doesn't work

### ISSUE THREAD

**Issue by Manalro** [avanzu/AdminThemeBundle#230]
I have an issue when I am trying to launch this command :
`php bin/console avanzu:admin:fetch-vendor`

I have the folling error :
`[Executing] /usr/local/bin/bower install
[Error] The system cannot find the path specified.`

Also, I have installed bower via `npm install -g bower`

### Debug info
| ------------- | ------------- |
| Symfony version  | 3.4 |
| AdminThemeBundle  | 1.3.5  |

**Comment by craph** [comment]
@shakaran This issue seems occured on windows side because /usr/local/bin/bower is not defined on windows.

FEATURE REQUEST:

* Is there a possibility to get dynamically the bower installation dir ? it must be very helpful for user #231

What is the correct path to use on windows side ? **And please could you update the installation process to provide this issue in the future.**

**Comment by shakaran** [comment]
@craph @Manalro you have the option and parameter "bower_bin" to define the path instead if you use windows

https://github.com/avanzu/AdminThemeBundle/blob/master/Command/FetchVendorCommand.php#L38

Closing as invalid since it is not a issue. Thanks for your report

**Comment by craph** [comment]
But it's not defined in the installation process !!

That cause some many issues ...

And why the fetchVendor is needed  because all the library are in the almasaeed2010/adminlte package no ?

**Comment by shakaran** [comment]
@craph documentation is not extensive or updated. You always could make a PR

The fetch vendor is needed to pick the right assets, probably the original author implement this based in admintle package too, but I don't know exactly

**Comment by Manalro** [comment]
I added the path to bower into my config.yml, and this time when I execute the fetch vendor command it doesn't send me any error message yet it doesn't change anything in my files and it opens a window asking me to choose how do I want to open this file. Is this normal ?
