### ISSUE TITLE
Find bower installation dir dynamically

### ISSUE THREAD

**Issue by craph** [avanzu/AdminThemeBundle#231]
It would be very helpful for users if the path of the bower binary would be find dynamically for each operating system

FEATURE REQUEST:

  * Find bower binary dinamycally for each operating system
  * Impacted file : DependencyInjection/Configuration

| Component  | Version |
| ------------- | ------------- |
| Symfony version  | 3.x - 4.x  |
| AdminThemeBundle  | 1.3.5  |

**Comment by shakaran** [comment]
I don't know any way to detect a binary path from PHP in bower, if it is not in PATH or normal binary path. Anyways, it don't should be a thing that a bundle should do, it assume that you have bower installed and configure to your right path. I just add a small detection for check if WIN or others. This will be done and merge only in 2.x (aka master), not in 1.3.5 version.

**Comment by Manalro** [comment]
I added the path to bower into my config.yml, and this time when I execute the fetch vendor command it doesn't send me any error message yet it doesn't change anything in my files and it opens a window asking me to choose how do I want to open this file. Is this normal ?
