### ISSUE TITLE
Documentation link about using layout for 1.3 doesn't work

### ISSUE THREAD

**Issue by craph** [avanzu/AdminThemeBundle#235]
@shakaran please could you provide a correct link to explain how to use the layout based on the version 1.3

https://github.com/avanzu/AdminThemeBundle/blob/hotfix-1.3.5/Resources/docs/layout.md

| Component  | Version |
| ------------- | ------------- |
| Symfony version  | 3.4  |
| AdminThemeBundle  | 1.3.5 |
| Operating System  | Windows  |

**Comment by shakaran** [comment]
The branch hotfix-1.3.5 was removed and used 1.3.x instead

The links should be updated dinamically:
https://github.com/avanzu/AdminThemeBundle/blob/1.3.x/Resources/docs/layout.md

You can access anyways always from the tree:

https://github.com/avanzu/AdminThemeBundle/tree/1.3.x

Or via tag, for example specifically 1.3.5
https://github.com/avanzu/AdminThemeBundle/tree/1.3.5

Or lastest 1.3.x which is 1.3.11
https://github.com/avanzu/AdminThemeBundle/tree/1.3.11

If you detected some link broken in Readme or master branch, you can file a PR or report a new issue.

Closing this (reopen if you have some doubth or comment about it).
Thanks!
