### ISSUE TITLE
[Executing] /usr/local/bin/bower install

### ISSUE THREAD

**Issue by ashfaq17** [avanzu/AdminThemeBundle#242]
I am using windows and getting this error when I try to run command. 
I have node and bower installed

If this is a BUG REPORT:
$ php bin/console avanzu:admin:fetch-vendor
[Executing] /usr/local/bin/bower install
[Error] The system cannot find the path specified.

If this is a FEATURE REQUEST:

  * Describe the new feature briefly.
  * If you consider or have knowledge submit a Pull Request.

### Debug info

| Component  | Version |
| ------------- | ------------- |
| Symfony version  | Your current symfony version  |
| AdminThemeBundle  | 1.3.5/dev-master/specific-commit/tag  |
| Operating System  | Windows or GNU/Linux or other  |

**Comment by englenshan** [comment]
add configure in comfig.yml
avanzu_admin_theme:
    bower_bin: 'your bower bin path'

**Comment by shakaran** [comment]
As described by @englenshan you need define the bower_bin path in config if you are using other than default path. Closing as solved
