### ISSUE TITLE
 Command "avanzu:admin:initialize" is not defined.

### ISSUE THREAD

**Issue by ashfaq17** [avanzu/AdminThemeBundle#244]
**Command not working:** 
php bin/console avanzu:admin:initialize

  Command "avanzu:admin:initialize" is not defined.

  Did you mean one of these?
      avanzu:admin:build-assets
      avanzu:admin:compact-vendor
      avanzu:admin:fetch-vendor

  * Describe the new feature briefly.
  * If you consider or have knowledge submit a Pull Request.

### Debug info

| Component  | Version |
| ------------- | ------------- |
| Symfony version : 3.4
| AdminThemeBundle : dev-master 
| Operating System : Windows

**Comment by shakaran** [comment]
This seems a duplicate of https://github.com/avanzu/AdminThemeBundle/issues/213 and future fix on PR #216

Closing as duplicate. Reopen or comment if you thinks otherwise. Thanks for your report!
