### ISSUE TITLE
Symfony doesn't found avanzu command

### ISSUE THREAD

**Issue by Cellendhill** [avanzu/AdminThemeBundle#246]
BUG REPORT:

I just install this bundle in my composer: "avanzu/admin-theme-bundle": "dev-master" 
and it seems that symfony doesn't founds avanzu commands, by the way i added the bundle in my AppKernel.php.

### Debug info

| Component  | Version |
| ------------- | ------------- |
| Symfony version  | v4.1  |
| AdminThemeBundle  | dev-master  |
| Operating System  | GNU/Linux  |

**Comment by oldy777** [comment]
Pull request on this issue wait from january (((
You can add commands in your service.yml file
```
Avanzu\AdminThemeBundle\Command\:
        resource: ../vendor/avanzu/admin-theme-bundle/Command
        tags: [console.command]
```

**Comment by Cellendhill** [comment]
Hello,

Thank you for your answer, I switch in the past to the repository "avanzu/admin-theme-bundle": "dev-kevinpapst", and it works, but yesterday, i've got an error on it, it doesn't have the directory "Command", so it canno't work anymore.

By the way, i switch back to "avanzu/admin-theme-bundle": "dev-master" and see your answer, so I add
```

    Avanzu\AdminThemeBundle\Command\InitializeCommand:
        tags: [console.command]
        public: true
    Avanzu\AdminThemeBundle\Command\BuildAssetsCommand:
        tags: [console.command]
        public: true
    Avanzu\AdminThemeBundle\Command\CompactVendorCommand:
        tags: [console.command]
        public: true
    Avanzu\AdminThemeBundle\Command\FetchVendorCommand:
        tags: [console.command]
        public: true

```
to my services.yml and it works again, thank you for your work.

**Comment by shakaran** [comment]
The branch with experimental support for symfony 4.x is under 
https://github.com/avanzu/AdminThemeBundle/tree/experimental-symfony-4.x

**Comment by shakaran** [comment]
To test experimental:
 
`composer require avanzu/admin-theme-bundle:dev-experimental-symfony-4.x`

or

` composer require shakaran/admin-theme-bundle:dev-experimental-symfony-4.x`

**Comment by shakaran** [comment]
@Cellendhill @oldy777 This is now solved is master branch. You can test if you want. Closing as solved
