### ISSUE TITLE
fonts give 404

### ISSUE THREAD

**Issue by glensc** [avanzu/AdminThemeBundle#25]
how the fonts are supposed to be accessed with assetic?

what i have is that `/css/9b199dd_part_1.css` url contains:

``` css
@font-face {
  font-family: 'FontAwesome';
  src: url('../fonts/fontawesome-webfont.eot?v=4.0.3');
  src: url('../fonts/fontawesome-webfont.eot?#iefix&v=4.0.3') format('embedded-opentype'), url('../fonts/fontawesome-webfont.woff?v=4.0.3') format('woff'), url('../fonts/fontawesome-webfont.ttf?v=4.0.3') format('truetype'), url('../fonts/fontawesome-webfont.svg?v=4.0.3#fontawesomeregular') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

which would request `/fonts/fontawesome-webfont.woff?v=4.0.3` ... and that's 404

when i find `.ttf` files, then those are only in vendor dir:

```
$ find -name '*ttf*'|xargs ls -ldrS|grep awes
-rwxrwxr-x 1 glen glen  80652 aug   13 15:55 ./vendor/avanzu/admin-theme-bundle/Resources/public/vendor/AdminLTE/fonts/fontawesome-webfont.ttf
-rw-rw-r-- 1 glen glen  80776 aug   13 15:48 ./vendor/avanzu/admin-theme-bundle/Resources/public/vendor/bootflat/fonts/fontawesome-webfont.ttf
-rw-rw-r-- 1 glen glen  80776 aug   13 15:37 ./vendor/avanzu/admin-theme-bundle/Resources/public/fonts/fontawesome-webfont.ttf
```

the .ttf could be accessible via /web/bundles, but it's not rewritten so in css:

```
$ ls -l web/bundles/avanzuadmintheme/fonts/fontawesome-webfont.ttf 
-rw-rw-r-- 1 glen glen 79K aug   13 15:37 web/bundles/avanzuadmintheme/fonts/fontawesome-webfont.ttf
```

**Comment by shakaran** [comment]
@glensc @szaman86 could you try testing with the new master branch and let me know if thi is still an issue? Waiting for you feedback if it is still an issue. Thanks!

**Comment by glensc** [comment]
@shakaran sorry no, i abandoned this package 3 years ago.

**Comment by shakaran** [comment]
@glensc sorry to hear that, I suppose you were waiting too much and give up. 

I fix the bug now and the fonts are coping in the right folder in case that you want use again the bundle in future or other users. Apologies for the delay and thanks for your report!
