### ISSUE TITLE
Upgrade AdminThemeBundle to use AdminLTE v2

### ISSUE THREAD

**Issue by pdesmarais** [avanzu/AdminThemeBundle#30]
Are there any plans for this?

Thanks!

**Comment by monsefoster** [comment]
I'd like to know this as well.

**Comment by pdesmarais** [comment]
I started working on it in a fork. I'll update the status here and create a pull request when I'm done.

**Comment by pdesmarais** [comment]
@monsefoster 
I've created a pull request of the update to use AdminLTEv2 (my fork: https://github.com/pdesmarais/AdminThemeBundle). If you want to try it out before it's merged in the main bundle, try this :

Add the following to your `composer.json`
```
    "repositories": [
        {
          "type": "vcs",
          "url": "https://github.com/pdesmarais/AdminThemeBundle"
        }
    ],
```

And a bit lower, when you require use this instead :
```
"avanzu/admin-theme-bundle": "dev-adminltev2",
```

Once that's done, next time you run composer update it should get my fork instead. Unless there are bugs (which I haven't seen for now), this should be stable.

You'll have to fetch-vendors again and use the base templates in the bundle to rebuild your project's templates because there's a few things that have changed in there.

Ping me if you need help.

**Comment by Giuseppe28** [comment]
Nice job pedesmarais, that's exactly what i need ^^ thanx a lot
