### ISSUE TITLE
Could this be used with KnpMenuBundle?

### ISSUE THREAD

**Issue by monsefoster** [avanzu/AdminThemeBundle#33]
I'm using this for the first time and I was wondering if there's anyway to incorporate KnpMenuBundle to use with side bars?

**Comment by avanzu** [comment]
In terms of rendering it would work. The Knp `MenuItemInterface` is pretty much identical to the Theme's `MenuItemInterface`. You would have to build some kind of wrapper/proxy for the KnpMenuItem (or fork this bundle and get rid of the MenuItemInterface type hints). 
Unfortunately, creating an inherited MenuItemInterface extending both is not possible.

**Comment by albertsola** [comment]
Would you mind if we migrate the menu to KnpMenuBundle?

I can have a look to it and implement it for the next release if you are happy with that.

The main reason is to reuse a pice of software that already exists and works quite well and it makes easier to migrate current projects to this theme or even extend it with more advanced third party menu systems.

**Comment by Arkadis** [comment]
+1

**Comment by avanzu** [comment]
Have a look at the 2.x pre-release which comes with KnpMenuBundle support.
