### ISSUE TITLE
Source Sans Pro not loaded

### ISSUE THREAD

**Issue by gperdomor** [avanzu/AdminThemeBundle#34]
Hi, i really like to use this bundle, but after install i notice that the page not showed like the AdminLTE demo and the problem was the font...

The CSS file have errors and is not valid, in fact, if you validate the CSS with the W3C CSS Validator (https://jigsaw.w3.org/css-validator/) you get a lot of errors and warnings, but the font related error is:

<code>
@import are not allowed after any valid statement other than @charset and @import. @import url(//fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic); 
</code>

**Comment by avanzu** [comment]
The `admin_lte_all_css` group was configured in the wrong order which leads to this issue. 
This should be fixed with the 1.3.0 release.
