### ISSUE TITLE
How can I restrict dates in date widget?

### ISSUE THREAD

**Issue by monsefoster** [avanzu/AdminThemeBundle#35]
This may be an stupid question, but I've tried all I could think of and no results.

**Comment by avanzu** [comment]
What exactly is meant with "restrict"? Allow any date except specific ones? 

If that's what you're looking for, the short answer is: no. 

 You could create a [field specific form block](http://symfony.com/doc/current/cookbook/form/form_customization.html#how-to-customize-an-individual-field) and add some javascript which does the actual restriction. Try [this fiddle](http://jsfiddle.net/k017daos/) for reference. 

Or for reusability, you could create your own form type, extending from the `DateType` (plus the aforementioned form block). 
That way you could also make use of the `setDefaults` method to add a configuration option for the dates you want to disallow like so: https://gist.github.com/avanzu/bb2d4b12113ed907b5ff#file-gistfile1-php

**Comment by shakaran** [comment]
@monsefoster are your question replied or you need more info about? Please let me know if you need additional clarification or the issue could be closed. Thanks

**Comment by monsefoster** [comment]
Hello @shakaran, I don't remember if I figured it out or never got back to the project itself. You can close this now, thank you

**Comment by monsefoster** [comment]
Hello @shakaran, I don't remember if I figured it out or never got back to the project itself. You can close this now, thank you
