### ISSUE TITLE
Hard dependency on Assetic

### ISSUE THREAD

**Issue by Jawan81** [avanzu/AdminThemeBundle#38]
The readme states 'there is no longer a strict requirement for bower and/or assetic' but in `Resources/views/layout/macros.html.twig` the usage of
```Twig
{% image '@avatar_img' %}
    <img src="{{ asset_url }}" class="{{ class|default('img-circle') }}" alt="{{ alt }}" />
{% endimage %}
```
creates a hard dependency on assetic.

**Comment by avanzu** [comment]
Took a while but is fixed in 1.3.4
