### ISSUE TITLE
app/console avanzu:admin:fetch-vendor 

### ISSUE THREAD

**Issue by Mendbayar** [avanzu/AdminThemeBundle#5]
when i run app/console avanzu:admin:fetch-vendor, there is a error like below on windows 7. 

D:\Bitnami\wampstack-5.4.26-2\apache2\htdocs\Symfony>php app/console avanzu:admi
n:fetch-vendor
[Executing] /usr/local/bin/bower install
[Error] The system cannot find the path specified.
[Executing] git clone https://github.com/almasaeed2010/AdminLTE.git
PHP Warning:  proc_open(): CreateProcess failed, error code - 267 in D:\Bitnami\
wampstack-5.4.26-2\apache2\htdocs\Symfony\vendor\symfony\symfony\src\Symfony\Com
ponent\Process\Process.php on line 249

  [Symfony\Component\Process\Exception\RuntimeException]
  Unable to launch a new process.

avanzu:admin:fetch-vendor [-u|--update]

**Comment by talib570** [comment]
For windows if you install bower globally using `npm install -g bower` 
then just insert this in **app/config.yml**
`  avanzu_admin_theme:
          bower_bin: "bower "
`
and you'll be good to go...
