### ISSUE TITLE
Is this bundle still maintained ?

### ISSUE THREAD

**Issue by numerogeek** [avanzu/AdminThemeBundle#53]
Hello @avanzu ,

Is this bundle still maintained ? 
I have the feeling that PR & issues stays without response ?

**Comment by senol1** [comment]
I think so as it works well

**Comment by numerogeek** [comment]
Ok, just asking, because I see some PR and issues without response for a while.

**Comment by senol1** [comment]
Oh yes , the forum is far from being dynamic

**Comment by avanzu** [comment]
well... maintained with a grain of salt (or two) but we're working on it, as it seems.
