### ISSUE TITLE
Are we able to sort Sidebar Menu?

### ISSUE THREAD

**Issue by aftabnaveed** [avanzu/AdminThemeBundle#54]
I have  a few listeners for Sidebar Menu, and would like to sort those the way I want it,  is it currently possible?

**Comment by avanzu** [comment]
The menu structure itself ist currently not sortable. But since the menu items are placed according to the order of the event listeners, you could use the listener priority value to achieve a specific order. 

> There is an additional tag option priority that is optional and defaults to 0. The listeners will be executed in the order of their priority (highest to lowest). This is useful when you need to guarantee that one listener is executed before another.
> [symfony docs](http://symfony.com/doc/current/cookbook/event_dispatcher/event_listener.html)
