### ISSUE TITLE
Unable to find file "@AvanzuAdminThemeBundle/Resources/public/vendor/modernizr/modernizr.js".

### ISSUE THREAD

**Issue by OskarStark** [avanzu/AdminThemeBundle#55]
I am on the latest version and got this error:

<img width="940" alt="bildschirmfoto 2015-09-19 um 12 34 38" src="https://cloud.githubusercontent.com/assets/995707/9975807/d1366c30-5eca-11e5-9e70-ab7a39395a29.png">

**Comment by OskarStark** [comment]
<img width="1149" alt="bildschirmfoto 2015-09-19 um 12 35 07" src="https://cloud.githubusercontent.com/assets/995707/9975810/e2a8ceae-5eca-11e5-9887-5514bc1f01fd.png">

**Comment by OskarStark** [comment]
<img width="1151" alt="bildschirmfoto 2015-09-19 um 12 35 30" src="https://cloud.githubusercontent.com/assets/995707/9975812/f1b26568-5eca-11e5-9755-21975034a6c4.png">

**Comment by timwhite** [comment]
I also get the same problem.
I can see the Modernizr.js file is located at vendor/avanzu/admin-theme-bundle/Resources/public/vendor/modernizr/src/Modernizr.js
If I edit assets.php to point to this file then avanzu:admin:build-assets works and everything works.

**Comment by OskarStark** [comment]
@timwhite thanks for the hotfix, but i think this is a real bug, isn't it?

ping @chteuchteu @avanzu

**Comment by senol1** [comment]
Hi,
Me last time I manually download and placed in that directory:


2015-09-19 11:42 GMT+00:00 Oskar Stark <notifications@github.com>:

> @timwhite <https://github.com/timwhite> thanks for the hotfix, but i
> think this is a real bug, isn't it?
>
> ping @chteuchteu <https://github.com/chteuchteu> @avanzu
> <https://github.com/avanzu>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/avanzu/AdminThemeBundle/issues/55#issuecomment-141653894>
> .
>



-- 
Sény Mbaye
Etudiant en Master II
Génie Informatique option Génie Logiciel / UFR Sciences et Technologies
Université de THIES
Portable : (+221)775915416
*senyr9@gmail.com <senyr9@gmail.com>*

**Comment by chteuchteu** [comment]
Hi,

**Comment by chteuchteu** [comment]
Hi,

I updated to the latest version but I'm afraid I'm not experiencing your issue. What's the problem with the missing asset? Is the file path and name exactly the same as the one AdminThemeBundle is expecting?

@timwhite said that there is a "Modernizr.js" file, but ATB is actually expecting "modernizr.js"...

**Comment by murilodbva** [comment]
I had the same error and this worked for me:

**Install bower**
```
sudo apt-get install nodejs
sudo apt-get install npm
sudo npm install -g bower
sudo ln -s /usr/bin/nodejs /usr/bin/node
sudo apt-get install nodejs-legacy
```

```
git config --global url."https://".insteadOf git://
sudo php app/console avanzu:admin:fetch-vendor
sudo php app/console assets:install
```

**Reference:**
[http://www.codediesel.com/javascript/installing-bower-on-ubuntu-14-04-lts/](http://www.codediesel.com/javascript/installing-bower-on-ubuntu-14-04-lts/)
and a coworker. =)
