### ISSUE TITLE
difference betwen dev & prod

### ISSUE THREAD

**Issue by numerogeek** [avanzu/AdminThemeBundle#57]
Hey guys, 

I have a problem with the datatable. In dev environement, the filters icon appears to be a css class. In prod environment, the filters icon's seems to be a img ( located in bundles/avanzuadmintheme/static/prod/styles/images/sort_asc.png ) but this doesnt exists (event after cache:clear, assets install, assetic:dump or fetch-vendors...)

Thank you for helping :)

**Comment by numerogeek** [comment]
Hmm, the prod directory seems to be outdated here.

**Comment by hjanuschka** [comment]
had the same issue
2 solutions :)

using capifon to deploy my app into production - copying dev assets to prod

`invoke_command "sh -c 'cd #{latest_release}/web/bundles/avanzuadmintheme/static && cp -pva dev/* prod/'"`


or after deploy generate the prod assets :) - seems cleaner to me, but requires `uglifyjs` und `uglifycss` installed.

`invoke_command "sh -c 'cd #{latest_release} && app/console avanzu:admin:build-assets --env=prod'"`

**Comment by numerogeek** [comment]
Thank you @hjanuschka ,
an other solution I've found is to fetch vendors and install assets using the --env prod option.

    php app/console avanzu:admin:fetch-vendor

**Comment by hjanuschka** [comment]
`app/console avanzu:admin:fetch-vendor --env=prod`didn't work for me :D

**Comment by numerogeek** [comment]
@hjanuschka thank for pointing this out :)
if you like this adminthemebundle, have a look on this boilerplate I've made to kickstart project in a minute !  https://github.com/numerogeek/ultimate-symfony2-boilerplate

**Comment by avanzu** [comment]
After fetching the vendor scripts (which should be optional since 1.3.0) you will need to regenerate the static assets as [described here](
https://github.com/avanzu/AdminThemeBundle/blob/master/Resources/docs/rebuild.md). The upgrade notice is obviously not very clear about that.
