### ISSUE TITLE
Angular JS support

### ISSUE THREAD

**Issue by aftabnaveed** [avanzu/AdminThemeBundle#58]
Right now AvanzuAdmin Bundle has doctype html tag outside of any twig block Angular JS requires ng-app attribute for that tag, is there a way to add it? or do I need to make the change in core layout?

**Comment by avanzu** [comment]
You could simply override the templates inside of your project as described in the [Symfony docs](http://symfony.com/doc/current/book/templating.html#overriding-bundle-templates).

**Comment by aftabnaveed** [comment]
Again, I wanted to avoid overriding the entire template in my custom Bundle and would have liked to put <html> and body tags inside a block may be some thing like html_start and body_start, but I appreciate your answer and would love to contribute if those changes or additions would make sense.

**Comment by avanzu** [comment]
I see your point. Maybe you could [make use of use](http://twig.sensiolabs.org/doc/tags/use.html) then?
Thinking of js-framework integration in general, it might be useful to introduce specialized layouts which fit the common needs of a specific framework. 

Anyways, adding those blocks to the base layout seems to be useful. Please feel free to open a pull request.  :+1:

**Comment by shakaran** [comment]
Implemented the block tags that support Angular JS use in https://github.com/avanzu/AdminThemeBundle/commit/201d8991bd2931e79197d9c832536af193239a39. Also doc updated. Closing this issue. Thanks for your report!
