### ISSUE TITLE
How to use your adminthemebundle templates in my sf 2 project

### ISSUE THREAD

**Issue by Mendbayar** [avanzu/AdminThemeBundle#6]
How to use your adminthemebundle twig templates in my sf 2 project. Please show me easy example such as showing login page or home page template.

**Comment by aftabnaveed** [comment]
though this issue is closed, even though I run above commands  but I still get the exception, I am using 1.3 version.

**Comment by 2ndkauboy** [comment]
The `avanzu:admin:fetch-vendor` command fails, as there are inaccurate version numbers in the bower.json file, which results in a confilct for underscore.

@avanzu: Please do not just use `*` as a version number for the dependencies. This will fail quite often. For underscore, you might use something like `~1.8` or similar.

@aftabnaveed: To get the bundle running, use the following:
`cd vendor/avanzu/admin-theme-bundle/Resources/bower/`
`bower install`

You should than be asked for the version number, you want to use. Just select the option with the largest version number (in my case, this was `6`).
