### ISSUE TITLE
correct way to use adminlte plugins

### ISSUE THREAD

**Issue by hjanuschka** [avanzu/AdminThemeBundle#62]
what is the real way to use e.g.: jquery.flot.pie.js

right now i use the following in my template:

<script src="{{ asset('bundles/avanzuadmintheme/vendor/adminlte/plugins/flot/jquery.flot.js') }}"></script>
        <script src="{{ asset('bundles/avanzuadmintheme/vendor/adminlte/plugins/flot/jquery.flot.pie.js') }}"></script>

is this best practice? :D

**Comment by fr05t1k** [comment]
Do you find the correct way?

**Comment by hjanuschka** [comment]
no - i'v been using the method above - now for ages. 
haven't had a problem.


we recently switched to `feature/2.0` branch and even there it seems to be (slightly different)

```
<script src="{{ asset('theme/plugins/datatables/jquery.dataTables.js') }}"></script>
```

so i guess it is the correct way.

**Comment by fr05t1k** [comment]
@hjanuschka thanks ;)

**Comment by hjanuschka** [comment]
using it for along time as described above, no problems so far, so i guess it is right!
