### ISSUE TITLE
Different font awesome versions on dev and prod

### ISSUE THREAD

**Issue by surivrox** [avanzu/AdminThemeBundle#65]
After deploy on production I noticed that not all FA icons are loaded. I discovered that on dev we have FA in version 4.4.0 but on production we have 4.2.0. How can I use the 4.4.0 on production?

https://github.com/avanzu/AdminThemeBundle/blob/master/Resources/public/static/dev/styles/admin-lte-all.css <- 4.4.0
https://github.com/avanzu/AdminThemeBundle/blob/master/Resources/public/static/prod/styles/admin-lte-all.css < 4.2.0

**Comment by chteuchteu** [comment]
It seems that someone updated it in one file but not another.
Could you open a pull request to fix the issue?
