### ISSUE TITLE
Icons in sub-children

### ISSUE THREAD

**Issue by MartinLyne** [avanzu/AdminThemeBundle#69]
I know icons in subchildren aren't native to AdminLTE, but I find it a nice addition. Would it be worth submitting the PR to make it work? Or is it considered out-of-scope?

I'm just overriding the macros template in my app/Resources at the minute.

Change is here: https://github.com/avanzu/AdminThemeBundle/compare/master...MartinLyne:patch-1

Edit: Also, how do I put label on this to question?

**Comment by OskarStark** [comment]
i like your idea :+1:

**Comment by sylvaincombes** [comment]
I like it too :+1:

**Comment by chteuchteu** [comment]
That's a good contribution indeed. I think that we could enhance AdminLTE a bit with this kind of enhancements.

@MartinLyne : do you want to create a pull request on your own, or should we merge @sylvaincombes 's one?

**Comment by MartinLyne** [comment]
Sorry for absence, great, seems @sylvaincombes PR (or my forked repo more likely) suffers the same issue I get whenever I try to modify files via github's editor, I'll make a new branch and edit code/documentation via normal means and make a new PR, see if that works.

**Comment by chteuchteu** [comment]
Hi! No problem.
The best way to be to:

1. Clone your fork locally
2. [Sync it](https://help.github.com/articles/syncing-a-fork/)
3. Create a branch
4. Make your changes, commit, push and create a PR from this branch

This will allow you to be up to date with the master branch and be sure that your PRs will be accepted :)

Thank you for your contribution!

**Comment by MartinLyne** [comment]
@chteuchteu Yeah it's much easier locally, I guess github doesn't warn you that forked projects are out of sync

Now I update, i notice that there has been a significant change to the way the sidebar nav works in this commit: https://github.com/avanzu/AdminThemeBundle/commit/75c1d75983f701da9d7664a668cad9badaf2b747

Seems that top-level items with no route can no longer host children, does that look like an oversight I should amend, or is it desired restriction? Probably want to drop into child-bearing code if it has a route or it has children? (I'll give it a go)

**Comment by chteuchteu** [comment]
That's unfortunate indeed... I don't know if it is a desired restriction, but anyways: I don't think that we should stick with this restriction.

Could you give it a try please?

**Comment by MartinLyne** [comment]
That fix seems to work, I think worst case is we go back to whatever could have happened before, my non-route-with-children examples work okay, I added some top-levels-without-routes-no-children and they display as I think they should. 

I'll prep the PR

**Comment by chteuchteu** [comment]
Thank you for your work, I just merged the PR.

**Comment by sylvaincombes** [comment]
Great :metal: thanks to @MartinLyne @OskarStark @chteuchteu ! (I closed the pull request made from @MartinLyne first patch)

**Comment by MartinLyne** [comment]
Brilliant! https://www.youtube.com/watch?v=S65ZzffW-Cw

**Comment by OskarStark** [comment]
:+1:
