### ISSUE TITLE
Unable to find file

### ISSUE THREAD

**Issue by deltaboypt** [avanzu/AdminThemeBundle#70]
Hello,
I try the AdminThemBundle for the first time and I have a stange issue already reported from other user but I can't solve it.

" Unable to find file "@AvanzuAdminThemeBundle/Resources/public/vendor/modernizr/modernizr.js" in . (which is being imported from "C:\xampp\htdocs\alcrm\app\cache\dev/assetic/routing.yml").
500 Internal Server Error - FileLoaderLoadException
1 linked Exception:
InvalidArgumentException » "

Can you help me please? Thanks

**Comment by MartinLyne** [comment]
Have you installed bower and run `php app/console avanzu:admin:fetch-vendor`

This installs modernizr (and some other assets AdminLTE needs)

**Comment by avanzu** [comment]
modernizr is now pinned to <= 3.0 which should resolve this issue.
