### ISSUE TITLE
Symfony 2.8/3.0 compatibility

### ISSUE THREAD

**Issue by paquitodev** [avanzu/AdminThemeBundle#76]
Easy question: is this bundle ready for Symfony 2.8/3.0 project?

**Comment by chteuchteu** [comment]
It is for Symfony 2.8, but you may have deprecation warnings.
It may not be for Symfony 3.0, we would have to fix things first.

You could update / create your project using Symfony 2.8 to be sure about this :)

**Comment by paquitodev** [comment]
@chteuchteu already on it, Symfony 2.8 project working on setup now!

**Comment by chteuchteu** [comment]
Thanks! I'll check deprecation warnings to fix them if necessary

**Comment by paquitodev** [comment]
thx, I will keep you posted if found anything ;)
