### ISSUE TITLE
Unexpected "image" tag (expecting closing tag for the "if" tag defined near line 34)

### ISSUE THREAD

**Issue by paquitodev** [avanzu/AdminThemeBundle#77]
I am trying to use the bundle in a Symfony 2.8 project and found the first issue:

> Unexpected "image" tag (expecting closing tag for the "if" tag defined near line 34) in 
> AvanzuAdminThemeBundle:layout:macros.html.twig at line 34.

This is the only code I have on the `index.html.twig` template:

    {% extends 'AvanzuAdminThemeBundle:layout:base-layout.html.twig' %}
    
    {% block page_content %}
        Hello World!
    {% endblock %}

**Comment by chteuchteu** [comment]
I achieved to reproduce this issue. This seems to come from assetic, but I haven't found a fix yet.

I'll keep your updated

**Comment by chteuchteu** [comment]
Assetic is indeed not shipped anymore with symfony since version 2.8. I added [installation instructions](https://github.com/avanzu/AdminThemeBundle#symfony-28-notice) in the main README.

Installing composer solves this issue ; thank you for your help!

**Comment by paquitodev** [comment]
@chteuchteu I'm working in [this][1] so I am overwriting the base-layout template at `app/Resources/AdminThemeBundle/views/layout/base-layout.html.twig` but even after get assetic installed and after run `assetic:dump`, `assets:install` commands I am getting this error now:

> Unable to find file "@AvanzuAdminThemeBundle/Resources/public/vendor/modernizr/modernizr.js" 
> in . (which is being imported from "/var/www/html/platform-cm/app/cache/dev/assetic/routing.yml")

Could you point me on the right path to fix this and made a pull request regarding the other issue? Solution is easy one just setting that var at `app/config/config.yml` under `twig => globals` but I need to fix this and test before answer in the other issue

 [1]: https://github.com/avanzu/AdminThemeBundle/issues/78

**Comment by chteuchteu** [comment]
Did you run `php app/console avanzu:admin:fetch-vendor`?

For the other issue, I think we could update the documentation to include the twig global trick (good catch, didn't thought about it) in the `layout.md` file
