### ISSUE TITLE
Change|overwrite default settings

### ISSUE THREAD

**Issue by paquitodev** [avanzu/AdminThemeBundle#78]
I have read docs and didn't found a way to change for example the `admin_skin` for other than default, could you point me on the right direction to achieve this?

**Comment by chteuchteu** [comment]
That's a great question. I checked: for now, there is no way to configure the admin_skin, even if the syntax tell the opposite.

The dirty hack is to edit the `vendor/avanzy/admin-theme/bundle/Resources/views/layout/base-layout.html.twig` file on your project (and add a rule to your .gitignore), but it's really not recommended. (a further update could overwrite this file)

Don't hesitate to create a pull request to add this feature.

**Comment by paquitodev** [comment]
So @chteuchteu here is my speedy solution to this issue without too much changes on bundle. Just setup each vars (not only one this one refer to admin_skin, people will need to look over templates) under `twig` at `app/config/config.yml` like below:

    # Twig Configuration
    twig:
        ...
        globals:
            admin_skin: "%admin_skin%"

Then redefine whatever you need in `app/config/parameters.yml` as I did:

     admin_skin: skin-blue-light

Of course those values need to be valid so check AdminLTE docs. That's all. I have tested and it works.

**Comment by chteuchteu** [comment]
Nice! IMO, the value should directly be defined in `config.yml`, since it is shared between instances. 

Could it be possible to add valid values for this parameter in the documentation as well? (with a link to AdminLTE documentation / code for reference)

**Comment by paquitodev** [comment]
@chteuchteu Ok, I will made a PR later with this

**Comment by chteuchteu** [comment]
Thanks!

**Comment by chteuchteu** [comment]
Thanks for the PR!
