### ISSUE TITLE
Double Side Bar menu

### ISSUE THREAD

**Issue by ghost** [avanzu/AdminThemeBundle#80]
Hi, 

I have setup your template, and follow the step of the Sidebar Nav readme.
But I now have 2 Menu, mine and under the SidebarSetupMenuDemoListener.
How can I remove this second one?

Thanks

**Comment by shakaran** [comment]
The use ghost seems deleted from github. Closing the issue since no user to interact. Please if someone has this issue reopen again. Thanks
