### ISSUE TITLE
Change harcoded string in form theming

### ISSUE THREAD

**Issue by shakaran** [avanzu/AdminThemeBundle#82]
On the file:

https://github.com/avanzu/AdminThemeBundle/blob/master/Resources/views/layout/form-theme.html.twig#L159

In the span, the title text should be a string with l18n support at least for the phrase "Dies ist ein Pflichtfeld":

```
<span class="required" title="Dies ist ein Pflichtfeld">*</span>
```

**Comment by chteuchteu** [comment]
That should get translated indeed... Could you open a pull request for this please?

**Comment by avanzu** [comment]
Dammit, you're totally right. Will be translatable in the 2.0 release. 
In the meantime please override the form-theme.html.twig. Sorry for that. :(

**Comment by shakaran** [comment]
This issue has been resolved as far I could check:

https://github.com/avanzu/AdminThemeBundle/blob/master/Resources/views/layout/form-theme.html.twig#L165

So closing my own issue, since I have the permissions enough! ;)
