### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by MrMitch** [avanzu/AdminThemeBundle#84]
I see that some pull requests that solve some problems I have with the bundle (namely #66 #68 and #73) have been merged but there has been no new release including them. Could you please release a new version or allow the other maintainers to release a new version ?
Thank you for your time.

**Comment by MrMitch** [comment]
cc @avanzu

**Comment by chteuchteu** [comment]
That would be great indeed!

**Comment by avanzu** [comment]
Done. Thanks everyone who contributed to this release.
