### ISSUE TITLE
stylesheets issue

### ISSUE THREAD

**Issue by Tetdoss** [avanzu/AdminThemeBundle#87]
Hello i'm using your awesome plugin but I have some issues : 

I can't add my own stylesheets by using a filter :

{% block stylesheets %}
{{ parent() }}

{% stylesheets
    'plugins/jQueryColorPicker/js/colorpicker.js'
    filter='cssrewrite' %}
    < link rel="stylesheet" href="{{ asset_url }}" />
{% endstylesheets %}

{% endblock %}

Thank you

**Comment by Tetdoss** [comment]
Fixed, i needed to add by bundle to assetic (symfony 2.8)

But the error wasn't explicit because it was an error saying in breadcrumb.html.twig that route avanzu_admin_home doesn't exist (line 3), but i'm using my own breadcrumb.html.twig...

So when there is a Symfony error, it uses your breadcrumb.html.twig... not mine :/ strange

**Comment by Tetdoss** [comment]
And can you translate the title on * (required field), Dies ist ein Pflichtfeld. thanks

**Comment by richard-fizz** [comment]
It should be available as a translation in a messages file.
Refer to http://symfony.com/doc/current/components/form/introduction.html#translation

**Comment by Tetdoss** [comment]
I fixed it by using braincrafted bootstrap instead. Append and prepend for fields work with braincrafted as opposed to avanzu :/

**Comment by richard-fizz** [comment]
If you want to append data or HTML to your form fields you should still be able to do that. You can either use form themes for that or override the default AvanzuAdminThemeBundle views by adding the corresponding names to app/Resources/views/<view name>

http://symfony.com/doc/current/cookbook/form/form_customization.html#form-theming-in-twig
http://symfony.com/doc/current/book/templating.html#overriding-bundle-templates

**Comment by shakaran** [comment]
@Tetdoss the translation to required should be now fixed in new versions, check when you can

**Comment by shakaran** [comment]
Closing since this seems fixed. Please reopen if you still have problems
