### ISSUE TITLE
Breadcrumbs menu documentation missing

### ISSUE THREAD

**Issue by richard-fizz** [avanzu/AdminThemeBundle#88]
The breadcrumbs documentation is missing:
https://github.com/avanzu/AdminThemeBundle/blob/master/Resources/docs/breadcrumbs.md

**Comment by MrMitch** [comment]
:+1: 
https://github.com/avanzu/AdminThemeBundle/blob/master/Resources/docs/component_events.md references it

**Comment by chteuchteu** [comment]
@richard-fizz : If you could help documenting it, that would be great!
@avanzu : Could you help us on this?
