### ISSUE TITLE
How to use calendar ?

### ISSUE THREAD

**Issue by falexis77** [avanzu/AdminThemeBundle#91]
which files js and css implement to use the calendar ?
how to have a link on left sidebar ?

Thanks

**Comment by chteuchteu** [comment]
This is not AdminThemeBundle-specific. Please read [AdminLTE's documentation](https://almsaeedstudio.com/themes/AdminLTE/documentation/index.html) to learn more

Create a page, put the calendar in it, and add a menu item leading to your page's route - follow AdminThemeBundle documentation to learn more about adding items to your menu.
