### ISSUE TITLE
How to implement the User authentication?

### ISSUE THREAD

**Issue by darthf1** [avanzu/AdminThemeBundle#99]
Hi. Thank you for this bundle. I dont fully understand how to use the User entity with the User sidebar/navbar. 

My current setup is that I've implement FOSUserBundle and get the user `$tokenStorage->getToken()->getUser();` in the `MyShowUserListener`. When accessing the route `/profile/{id}` however I get an error message: `Unable to find the controller for path "/profile/1/". The route is wrongly configured`. This is probably due to the fact that these routes also exists in the FOSUserBundle, but I am currenly uncertain how to implement the User part with this bundle in general.

**Comment by Kiriax** [comment]
Hi, I've a problem with the implementation of the User authentication.
 in the getUser i do this : 
`    protected function getUser() {
        /** @var User $user */
        $user = $this->container->get('security.token_storage')->getToken()->getUser();
        return $user;
    }`

but when i'm running the app, i've the error : 

> Error: Maximum function nesting level

Have you got the same problem ? Because with the same code, the implementation of sidebar user is correct.
